import streamlit as st

# ページ設定：まあ、見た目は大事ですからね
st.set_page_config(page_title="Slide Structure Optimizer", layout="wide")

st.title("Slide Structure Optimizer for NotebookLM")
st.markdown("""
会議の文字起こしから「スライド構成」と「NoteBook LM用指示書」を生成するだけのアプリです。
思考の整理はAIに投げてください。
""")

# --- サイドバー設定 ---
st.sidebar.header("設定パラメーター")

# 目的別パターンの定義 
# これを選ぶだけで仕事をした気になれる、魔法のプルダウンです
purpose_options = {
    "社内会議用：報告共有": "事実関係の正確な伝達と、現状の課題・ネクストアクションの共有。",
    "社内会議用：承認獲得": "決裁者が意思決定しやすいよう、メリット・デメリット・ROIを強調。",
    "社外資料：営業資料": "顧客の課題解決（ソリューション）を軸に、魅力的なオファーを提示。",
    "社外資料：企画提案": "新規性・実現可能性・収益性をバランスよく配置。",
    "社内資料：企画提案": "リソース配分と戦略的整合性を重視。",
    "社外資料：情報共有": "業界動向やナレッジを平易かつ体系的に整理。"
}

selected_purpose = st.sidebar.selectbox(
    "1. 資料作成の目的を選択",
    list(purpose_options.keys())
)

# YAMLトーン＆マナーの定義 [cite: 31]
# NoteBook LMの「人格」を操るための呪文ですね
yaml_styles = {
    "コンサル風（ロジカル）": "論理的整合性を重視し、MECEな構造と断定的な語尾を使用。",
    "カジュアル風（親しみ）": "口語体を交え、共感を呼ぶ柔らかい表現。",
    "社内協議用（フォーマル）": "客観的事実に基づき、感情を排した硬めの文体。",
    "社外営業用（アトラクティブ）": "形容詞を効果的に使い、期待感を醸成するエモーショナルな文体。",
    "アカデミック風（厳密）": "出典や根拠を明示し、専門用語を適切に使用。",
    "ストーリーテリング重視": "起承転結を意識し、物語として読ませる構成。",
    "エグゼクティブサマリー": "詳細は省き、結論とインパクトのみを箇条書きで。",
    "Q&Aベース": "想定問答形式で、疑問を先回りして解消するスタイル。",
    "ビジョナリー（未来志向）": "現状よりも「あるべき姿」や将来の展望を熱く語る。",
    "ミニマル（事実のみ）": "装飾を削ぎ落とし、データと事実のみを淡々と記述。"
}

selected_style = st.sidebar.selectbox(
    "2. NoteBook LMのトーン（YAML）を選択",
    list(yaml_styles.keys())
)

# --- メインエリア ---

st.subheader("STEP 1: 文字起こしデータの入力")
transcript = st.text_area(
    "ここに会議の文字起こし（ローデータ）を貼り付けてください ",
    height=200,
    placeholder="例：Aさん: えー、本日の議題ですが..."
)

# プロンプト生成ロジック
if transcript:
    st.divider()
    
    # 構成作成プロンプトの生成
    st.subheader("STEP 2: LLM用 構成作成プロンプト")
    st.info("以下のテキストをコピーして、Gemini 1.5 Pro や ChatGPT に貼り付けてください。")
    
    prompt_template = f"""
    # 指令
    あなたは優秀なビジネスコンサルタントです。以下の「会議文字起こし」を元に、指定された「目的」に沿ったスライド構成案を作成してください。

    # 目的
    {selected_purpose}
    （詳細定義: {purpose_options[selected_purpose]}）

    # 制約条件
    - スライド枚数は5〜10枚程度。
    - 各スライドには「タイトル」「ボディ（箇条書き）」「スピーカーノート」を含めること。
    - 余計な前置きは不要。出力はMarkdown形式で行うこと。

    # 会議文字起こしデータ
    {transcript}
    """
    
    st.code(prompt_template, language="markdown")
    
    st.divider()

    # YAML設定の生成
    st.subheader("STEP 3: NoteBook LM用 YAML設定")
    st.info("以下の設定コードをコピーするか、構成案と一緒にNoteBook LMに入力してください。")
    
    yaml_template = f"""
    # NoteBook LM Instruction YAML
    model_instruction:
      role: "Professional Presentation Designer"
      tone: "{selected_style.split('（')[0]}"
      style_description: "{yaml_styles[selected_style]}"
      output_format: "Slide Presentation Script"
      
    # User Requirement
    上記のトーン＆マナーを厳守し、アップロードされたスライド構成案に基づいて、
    聴衆を惹きつける具体的なスライド記述を生成してください。
    """
    
    st.code(yaml_template, language="yaml")

    st.divider()
    
    # 疑似的なダウンロード機能 
    # 本当はPDF化したいところですが、まずはテキストで構造を渡せれば十分でしょう
    st.subheader("おまけ: 素材のダウンロード")
    combined_text = f"--- PROMPT ---\n{prompt_template}\n\n--- YAML SETTING ---\n{yaml_template}"
    st.download_button(
        label="プロンプトと設定をテキストファイルでダウンロード",
        data=combined_text,
        file_name="slide_generation_kit.txt",
        mime="text/plain"
    )

else:
    st.warning("まずは文字起こしデータを入力してください。話はそれからです。")

# フッター
st.markdown("---")
st.caption("Generated by Naruyoshi Yugu Logic. 従量課金は敵だ[cite: 7].")